org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
android.useAndroidX=true
kotlin.code.style=official

GROUP=io.github.halilozel1903
VERSION_NAME=1.0.0

POM_URL=https://github.com/halilozel1903/compose-wear-timer
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/halilozel1903/compose-wear-timer
POM_SCM_CONNECTION=scm:git:git://github.com/halilozel1903/compose-wear-timer.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/halilozel1903/compose-wear-timer.git
POM_DEVELOPER_ID=halilozel1903
POM_DEVELOPER_NAME=Halil Özel
POM_DEVELOPER_URL=https://github.com/halilozel1903
